/*
-- Query: SELECT * FROM movies.movies
LIMIT 0, 1000

-- Date: 2022-11-29 14:43
*/
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('001','Avatar','Science Fiction',2009,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('002','Avengers: Endgame','Action',2019,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('003','Titanic','Drama',1997,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('004','Star Wars: Episode VII - The Force Awakens','Science Fiction',2015,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('005','Avengers: Inifinity War','Action',2018,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('006','Spider-Man: No Way Home','Adventure',2021,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('007','Jurassic World','Action',2015,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('008','The Lion King','Adventure',2019,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('009','The Avengers','Action',2012,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('010','Furious 7','Action',2015,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('011','Top Gun: Maverick','Action',2022,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('012','Frozen II','Adventure',2019,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('013','Avengers: Age of Ultron','Action',2015,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('014','Black Panther','Action',2018,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('015','Harry Potter and the Deathly Hallows: Part 2','Adventure',2011,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('016','Star Wars: Episode VIII- The Last Jedi','Science Fiction',2017,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('017','Jurassic World- Fallen Kingdom','Action',2018,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('018','Frozen','Adventure',2013,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('019','Beauty and the Beast','Drama',2017,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('020','Incredibles 2','Action',2018,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('021','The Fate of the Furious','Action',2017,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('022','Iron Man 3','Action',2013,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('023','Minions','Comedy',2015,'ENG','PG');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('024','Captain America: Civil War','Action',2016,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('025','Aquaman','Adventure',2018,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('026','The Lord of the Rings: The Return of the King','Adventure',2003,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('027','Spider-Man: Far from Home','Adventure',2019,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('028','Captain Marvel','Action',2019,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('029','Transformers: Dark of the Moon','Action',2011,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('030','Jurassic Park','Action',1993,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('031','Skyfall','Action',2012,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('032','Joker','Drama',2019,'ENG','R');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('033','Transformers: The Age of Extinction','Action',2014,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('034','The Dark Knight Arises','Drama',2012,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('035','Star Wars: Episode IX- The Rise of Skywalker','Science Fiction',2019,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('036','Toy Story 4','Comedy',2019,'ENG','G');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('037','Toy Story 3','Comedy',2010,'ENG','G');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('038','Pirates of the Carribean: On Stranger Tides','Action',2006,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('039','Despicable Me 3','Comedy',2017,'ENG','PG');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('040','Finding Dory','Comedy',2016,'ENG','PG');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('041','Star Wars: Episode 1- The Phantom Menace','Science Fiction',1999,'ENG','PG');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('042','Alice in Wonderland','Adventure',2010,'ENG','PG');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('043','Rogue One: A Star Wars Story','Science Fiction',2016,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('044','Aladdin','Comedy',2019,'ENG','PG');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('045','Zootopia','Comedy',2016,'ENG','PG');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('046','Harry Potter and the Sorcerer\'s Stone','Adventure',2001,'ENG','PG');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('047','The Hobbit: An unexpected Journey','Adventure',2012,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('048','The Dark Knight','Action',2008,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('049','Jurassic World: Dominion','Action',2022,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('050','Harry Potter and the Deathly Hallows: Part 1','Action',2010,'ENG','PG');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('051','Desicable Me 2','Comedy',2013,'ENG','PG');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('052','The Jungle Book','Adventure',2016,'ENG','PG');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('053','Jumanji: Welcome to the Jungle','Adventure',2017,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('054','The Hobbit: The Battle of the five Armies','Adventure',2014,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('055','Pirates of the Carribean: At World\'s End','Action',2007,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('056','The Hobbit: The Desolation of Smaug','Adventure',2013,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('057','Doctor Strange in the Multiverse of Madness','Action',2022,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('058','The Lord of the Rings: The Two Towers','Adventure',2002,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('059','Harry Potter and the Order of the Phoenix','Adventure',2007,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('060','Finding Nemo','Adventure',2003,'ENG','G');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('061','Minions: the Rise of Gru','Comedy',2022,'ENG','PG');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('062','Harry Potter and the Half-Blood Prince','Adventure',2009,'ENG','PG');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('063','Shrek 2','Comedy',2004,'ENG','PG');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('064','Bohemian Rhapsody','Drama',2018,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('065','The Battle at Lake Changjin','Action',2021,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('066','The Lord of the Rings: The Fellowship of the Ring','Adventure',2001,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('067','Harry Potter and the Goblet Fire','Adventure',2005,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('068','Spider-Man 3','Adventure',2007,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('069','The Secret Life of Pets','Adventure',2016,'ENG','PG');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('070','Ice Age: Dawn of the Dinosaurs','Comedy',2009,'ENG','PG');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('071','Spectre','Action',2015,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('072','Harry Potter and the Chamber of Secrets','Adventure',2002,'ENG','PG');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('073','Spider-Man: Homecoming','Adventure',2017,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('074','Ice Age: Continental Drift','Comedy',2012,'ENG','PG');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('075','Batman v Superman: Dawn of Justice','Action',2016,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('076','Wolf Warrior 2','Action',2017,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('077','Star Wars: Episode III: revenge of the Sith','Science Fiction',2005,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('078','The Hunger Games: Catching Fire','Action',2013,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('079','Guardians of the Galaxy Vol. 2','Science Fiction',2017,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('080','Inside Out','Comedy',2015,'ENG','PG');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('081','Venom','Action',2018,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('082','Thor: Ragnarok','Action',2017,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('084','Inception','Action',2010,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('085','Transformers: The Revenge of the Fallen','Action',2009,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('086','Spider-Man','Adventure',2002,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('087','Wonder Woman','Action',2017,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('088','Hi, Mom','Comedy',2021,'ENG','PG');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('089','Independence Day','Action',1996,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('090','Fantastic Beasts and Where to Find Them','Adventure',2016,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('091','Shrek the Third','Comedy',2007,'ENG','PG');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('092','Coco','Comedy',2017,'ENG','PG');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('093','Jumanji: Next Level','Adventure',2019,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('094','Harry Potter and the prisoner of Azkaban','Adventure',2004,'ENG','PG');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('095','Pirates of the Carribean: dead Men Tell No Tales','Action',2017,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('096','E.T. the Extra-Terrestrial','Adventure',1982,'ENG','PG');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('097','Mission Impossible - Fallout','Action',2018,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('098','2012','Action',2009,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('099','Spider Man 2','Adventure',2004,'ENG','PG-13');
INSERT INTO `` (`MOV_ID`,`MOV_TITLE`,`MOV_GENRE`,`MOV_YEAR`,`MOV_LANG`,`MOV_RATING`) VALUES ('100','Indiana Jones and the Kingdom of the Crystal Skull','Action',2008,'ENG','PG-13');
